name: 'ESP-IDF Project Build'

on:
  # Triggers the workflow on tag create like v1.0, v2.0.0 and so on
  push:
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Cache esp-idf and its tools
        id: esp-idf-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/esp/esp-idf
            ~/.espressif
          key: ${{ runner.os }}-esp-5.0
        
      - run: |
          if echo ${{ steps.esp-idf-cache.outputs.cache-hit }} | grep -c "true"
          then 
            echo "Cache hit - skipping dependency installation"
          else
            sh ${{ github.action_path }}/install.sh
          fi
        shell: bash

      - run: |
          source ~/esp/esp-idf/export.sh
          cd ${{ github.workspace }}/remote_temp_reader
          idf.py set-target esp32
          idf.py build
        shell: bash
