name: 'ESP-IDF Project Build'

on:
  # Triggers the workflow on tag create like v1.0, v2.0.0 and so on
  push:
  workflow_dispatch:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: 'recursive'

      - name: Cache esp-idf and its tools
        id: esp-idf-cache
        uses: actions/cache@v3
        with:
          path: |
            ~/esp/esp-idf
            ~/.espressif
          key: ${{ runner.os }}-esp-5.0
        
      - run: |
        # Installing prerequisites
        echo "## Install prerequisites"

        export DEBIAN_FRONTEND=noninteractive

        sudo apt-get install -y git wget flex bison gperf python3 python3-pip python3-setuptools cmake ninja-build ccache libffi-dev libssl-dev dfu-util

        # Making Python 3 the default interpreter
        sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 10

        # Create the esp directory for repo download
        mkdir ~/esp
        cd ~/esp

        echo "## Download esp-idf repository"
        git clone --recursive --depth=1 --shallow-submodules https://github.com/espressif/esp-idf.git

        # Navigate to esp idf repository
        cd ~/esp/esp-idf

        # Installing tools
        echo "## Install esp-idf tools"

        # Install required tools
        ./install.sh

      - run: |
          source ~/esp/esp-idf/export.sh
          cd ${{ github.workspace }}/remote_temp_reader
          idf.py set-target esp32
          idf.py build
        shell: bash
